export enum OwnerEnum {
  BANK = "BANK",
  BANK_BOX = "BANK_BOX",
  GENERIC_BANK = "GENERIC_BANK",
  GENERIC_BANK_BOX = "GENERIC_BANK_BOX",
  MONEY = "MONEY",
  PAYMENT = "PAYMENT",
  INVOICE = "INVOICE"
}
