CREATE ROLE role_name WITH LOGIN PASSWORD 'safe_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT CONNECT ON DATABASE meu_banco TO role_name;

GRANT USAGE, CREATE ON SCHEMA public TO role_name;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO role_name;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO role_name;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO role_name;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO role_name;

GRANT USAGE ON LANGUAGE plpgsql TO role_name;
